<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst;net10.0-windows10.0.19041.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>LightningChartMauiExample</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <WindowsPackageType>None</WindowsPackageType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LCLA" Version="0.0.10" />
  </ItemGroup>
  <ItemGroup>
    <MauiAsset Include="Data\patient_10.csv" LogicalName="patient_10.csv" />
  </ItemGroup>
</Project>
